### ISSUE TITLE
Ruby 1.8.7 tests failing

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/puppet-opendaylight#34]
Travis is [showing](https://travis-ci.org/dfarrell07/puppet-opendaylight/jobs/49520422) a remarkably obtuse error for tests run with Ruby 1.8.7. I currently have no idea what it means. Because of #33, I'm not sure when it was introduced. *sigh*

```
$ bundle exec rake test
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
Cloning into 'spec/fixtures/modules/stdlib'...
remote: Counting objects: 6183, done.
remote: Total 6183 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (6183/6183), 1.23 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2643/2643), done.
Checking connectivity... done.
/home/travis/.rvm/rubies/ruby-1.8.7-p374/bin/ruby -I/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib:/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-support-3.2.0/lib /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
Total resources:   0
Touched resources: 0
Resource coverage:  -nan%
Untouched resources:
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:512:in `all_hooks_for': return from proc-closure (LocalJumpError)
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:564:in `process'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/flat_map.rb:11:in `map'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/flat_map.rb:11:in `flat_map'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:563:in `process'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:429:in `register_globals'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:394:in `set_it_up'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:361:in `subclass'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:253:in `describe'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:43:in `__send__'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:43:in `describe'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:82:in `__send__'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:82:in `describe'
	from /home/travis/build/dfarrell07/puppet-opendaylight/spec/classes/opendaylight_spec.rb:3
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/exe/rspec:4
/home/travis/.rvm/rubies/ruby-1.8.7-p374/bin/ruby -I/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib:/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-support-3.2.0/lib /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color failed
The command "bundle exec rake test" exited with 1.
Done. Your build exited with 1.
```

**Comment by dfarrell07** [comment]
The only remotely intelligible part is `'all_hooks_for': return from proc-closure (LocalJumpError)`

**Comment by dfarrell07** [comment]
I think the issue might be in Travis. There was once another repo called `puppet-opendaylight`, which was more of a scratch space I used when I was screwing around learning Puppet. Travis was set, at one point, to run against it. I have since deleted that repo, created this new one (called `dfarrell07-opendaylight` initially) and renamed it `puppet-opendaylight`. I think this process broke something in Travis.

Reasons:
* New builds (#33) aren't checked when I turn *off* the old repo in Travis.
* Even known-good builds that have passed previously fail with that hook-related message.

I think I'll try deleting everything Travis knows about both projects? If that's even possible. *sigh*

**Comment by dfarrell07** [comment]
Why it only fails for 1.8.7 I can't imagine. That data point doesn't seem to support the Travis-is-the-issue theory.

**Comment by dfarrell07** [comment]
It really doesn't seem worth the effort to fight with Travis to get 1.8.7 working. I don't care about supporting 1.8.7, since I've already decided I'm not supporting CentOS 6.5 (which used 1.8.7). CentOS 7 ships with Ruby 2.0.0.

**Comment by dfarrell07** [comment]
Stopped checking 1.8.7 in b02fa54b4ee127757050b0ef4a09f213e7583e0a, so this is done.
