### ISSUE TITLE
ODL service not starting for Ubuntu 14.04

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/puppet-opendaylight#88]
Using the new Docker-based Beaker tests for Ubuntu 14.04

```
[~/puppet-opendaylight]$ bundle exec rake ubuntu_1404_docker
```

Everything seems to work except for starting ODL's service via Upstart.

```
Failures:

  1) opendaylight class testing install methods should work idempotently with no errors
     Failure/Error: apply_manifest(pp, :catch_failures => true)
     Beaker::Host::CommandFailure:
       Host 'ubuntu-1404-docker' exited with 6 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.KRCklq
       Last 10 lines of output were:
       	Info: /Stage[main]/Opendaylight::Config/File[org.apache.karaf.features.cfg]: Filebucketed /opt/opendaylight/etc/org.apache.karaf.features.cfg to puppet with sum 2a4fb152cf5561dfca0ffec6de946602
       	Notice: /Stage[main]/Opendaylight::Config/File[org.apache.karaf.features.cfg]/content: content changed '{md5}2a4fb152cf5561dfca0ffec6de946602' to '{md5}a6974cc13166b3e24a819a4ba9158067'
       	Notice: /Stage[main]/Opendaylight::Config/File[org.apache.karaf.features.cfg]/owner: owner changed 'root' to 'odl'
       	Notice: /Stage[main]/Opendaylight::Config/File[org.apache.karaf.features.cfg]/group: group changed 'root' to 'odl'
       	Info: Class[Opendaylight::Config]: Scheduling refresh of Class[Opendaylight::Service]
       	Info: Class[Opendaylight::Service]: Scheduling refresh of Service[opendaylight]
       	Error: /Stage[main]/Opendaylight::Service/Service[opendaylight]: Could not evaluate: undefined method `[]' for nil:NilClass
       	Notice: /Stage[main]/Opendaylight::Service/Service[opendaylight]: Triggered 'refresh' from 1 events
       	Info: Creating state file /var/lib/puppet/state/state.yaml
       	Notice: Finished catalog run in 601.72 seconds
       
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/host.rb:311:in `exec'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/helpers/host_helpers.rb:73:in `block in on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/shared/host_manager.rb:115:in `run_block_on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/patterns.rb:35:in `block_on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/helpers/puppet_helpers.rb:469:in `block in apply_manifest_on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/shared/host_manager.rb:115:in `run_block_on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/patterns.rb:35:in `block_on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/helpers/puppet_helpers.rb:398:in `apply_manifest_on'
     # /home/daniel/.gem/ruby/gems/beaker-2.29.1/lib/beaker/dsl/helpers/puppet_helpers.rb:476:in `apply_manifest'
     # ./spec/spec_helper_acceptance.rb:72:in `block in install_odl'

  2) opendaylight class testing install methods Service "opendaylight" should be running
     Failure/Error: it { should be_running }
       expected Service "opendaylight" to be running
       
     # ./spec/spec_helper_acceptance.rb:97:in `block (2 levels) in generic_validations'

  3) opendaylight class testing install methods Process "java" should be running
     Failure/Error: it { should be_running }
       expected Process "java" to be running
       
     # ./spec/spec_helper_acceptance.rb:126:in `block (2 levels) in generic_validations'
```

**Comment by srisankethu** [comment]
#116 should cover this :+1:
